/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.models;

import java.util.*;

public class ObjectValueBuilder {
    //the instance to build
    private ObjectValue objectValue;

    /**
     * Default constructor to initialize the instance
     */
    public ObjectValueBuilder() {
        objectValue = new ObjectValue();
    }

    public ObjectValueBuilder id(String id) {
        objectValue.setId(id);
        return this;
    }

    public ObjectValueBuilder name(String name) {
        objectValue.setName(name);
        return this;
    }

    public ObjectValueBuilder type(String type) {
        objectValue.setType(type);
        return this;
    }

    public ObjectValueBuilder duration(String duration) {
        objectValue.setDuration(duration);
        return this;
    }

    public ObjectValueBuilder status(String status) {
        objectValue.setStatus(status);
        return this;
    }

    public ObjectValueBuilder recordStatus(String recordStatus) {
        objectValue.setRecordStatus(recordStatus);
        return this;
    }

    public ObjectValueBuilder tripTranslate(List<TripTranslate> tripTranslate) {
        objectValue.setTripTranslate(tripTranslate);
        return this;
    }

    public ObjectValueBuilder tripImage(TripImage tripImage) {
        objectValue.setTripImage(tripImage);
        return this;
    }

    public ObjectValueBuilder tripPlanItem(List<TripPlanItem> tripPlanItem) {
        objectValue.setTripPlanItem(tripPlanItem);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ObjectValue build() {
        return objectValue;
    }
}