/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.models;

import java.util.*;

public class OjseiofBuilder {
    //the instance to build
    private Ojseiof ojseiof;

    /**
     * Default constructor to initialize the instance
     */
    public OjseiofBuilder() {
        ojseiof = new Ojseiof();
    }

    public OjseiofBuilder status(boolean status) {
        ojseiof.setStatus(status);
        return this;
    }

    public OjseiofBuilder code(String code) {
        ojseiof.setCode(code);
        return this;
    }

    public OjseiofBuilder message(String message) {
        ojseiof.setMessage(message);
        return this;
    }

    public OjseiofBuilder objectValue(ObjectValue objectValue) {
        ojseiof.setObjectValue(objectValue);
        return this;
    }

    public OjseiofBuilder pageValue(String pageValue) {
        ojseiof.setPageValue(pageValue);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public Ojseiof build() {
        return ojseiof;
    }
}