/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class Ojseiof 
        implements java.io.Serializable {
    private static final long serialVersionUID = -3973109240294178471L;
    private boolean status;
    private String code;
    private String message;
    private ObjectValue objectValue;
    private String pageValue;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("status")
    public boolean getStatus ( ) { 
        return this.status;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("status")
    public void setStatus (boolean value) { 
        this.status = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("code")
    public String getCode ( ) { 
        return this.code;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("code")
    public void setCode (String value) { 
        this.code = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("message")
    public String getMessage ( ) { 
        return this.message;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("message")
    public void setMessage (String value) { 
        this.message = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("objectValue")
    public ObjectValue getObjectValue ( ) { 
        return this.objectValue;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("objectValue")
    public void setObjectValue (ObjectValue value) { 
        this.objectValue = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("pageValue")
    public String getPageValue ( ) { 
        return this.pageValue;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("pageValue")
    public void setPageValue (String value) { 
        this.pageValue = value;
    }
 
}
