/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.models;

import java.util.*;

public class TripTranslateBuilder {
    //the instance to build
    private TripTranslate tripTranslate;

    /**
     * Default constructor to initialize the instance
     */
    public TripTranslateBuilder() {
        tripTranslate = new TripTranslate();
    }

    public TripTranslateBuilder tripPlanId(String tripPlanId) {
        tripTranslate.setTripPlanId(tripPlanId);
        return this;
    }

    public TripTranslateBuilder language(String language) {
        tripTranslate.setLanguage(language);
        return this;
    }

    public TripTranslateBuilder name(String name) {
        tripTranslate.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TripTranslate build() {
        return tripTranslate;
    }
}