/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.models;

import java.util.*;

public class TripImageBuilder {
    //the instance to build
    private TripImage tripImage;

    /**
     * Default constructor to initialize the instance
     */
    public TripImageBuilder() {
        tripImage = new TripImage();
    }

    public TripImageBuilder id(String id) {
        tripImage.setId(id);
        return this;
    }

    public TripImageBuilder refId(String refId) {
        tripImage.setRefId(refId);
        return this;
    }

    public TripImageBuilder filePath(String filePath) {
        tripImage.setFilePath(filePath);
        return this;
    }

    public TripImageBuilder fileType(String fileType) {
        tripImage.setFileType(fileType);
        return this;
    }

    public TripImageBuilder sequence(String sequence) {
        tripImage.setSequence(sequence);
        return this;
    }

    public TripImageBuilder lastUpdate(long lastUpdate) {
        tripImage.setLastUpdate(lastUpdate);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TripImage build() {
        return tripImage;
    }
}