/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class TripPlanItem 
        implements java.io.Serializable {
    private static final long serialVersionUID = 532823661199373623L;
    private String id;
    private String refType;
    private Double estimatePrice;
    private String transitType;
    private String estimateTime;
    private String contentId;
    private String name;
    private String imageUrl;
    private String region;
    private String province;
    private String sequence;
    private String tripDay;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("refType")
    public String getRefType ( ) { 
        return this.refType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("refType")
    public void setRefType (String value) { 
        this.refType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("estimatePrice")
    public Double getEstimatePrice ( ) { 
        return this.estimatePrice;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("estimatePrice")
    public void setEstimatePrice (Double value) { 
        this.estimatePrice = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("transitType")
    public String getTransitType ( ) { 
        return this.transitType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("transitType")
    public void setTransitType (String value) { 
        this.transitType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("estimateTime")
    public String getEstimateTime ( ) { 
        return this.estimateTime;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("estimateTime")
    public void setEstimateTime (String value) { 
        this.estimateTime = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("contentId")
    public String getContentId ( ) { 
        return this.contentId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("contentId")
    public void setContentId (String value) { 
        this.contentId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("imageUrl")
    public String getImageUrl ( ) { 
        return this.imageUrl;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("imageUrl")
    public void setImageUrl (String value) { 
        this.imageUrl = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("region")
    public String getRegion ( ) { 
        return this.region;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("region")
    public void setRegion (String value) { 
        this.region = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("province")
    public String getProvince ( ) { 
        return this.province;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("province")
    public void setProvince (String value) { 
        this.province = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sequence")
    public String getSequence ( ) { 
        return this.sequence;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sequence")
    public void setSequence (String value) { 
        this.sequence = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("tripDay")
    public String getTripDay ( ) { 
        return this.tripDay;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("tripDay")
    public void setTripDay (String value) { 
        this.tripDay = value;
    }
 
}
