/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class TripImage 
        implements java.io.Serializable {
    private static final long serialVersionUID = 9016787016006734219L;
    private String id;
    private String refId;
    private String filePath;
    private String fileType;
    private String sequence;
    private long lastUpdate;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("refId")
    public String getRefId ( ) { 
        return this.refId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("refId")
    public void setRefId (String value) { 
        this.refId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("filePath")
    public String getFilePath ( ) { 
        return this.filePath;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("filePath")
    public void setFilePath (String value) { 
        this.filePath = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fileType")
    public String getFileType ( ) { 
        return this.fileType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fileType")
    public void setFileType (String value) { 
        this.fileType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("sequence")
    public String getSequence ( ) { 
        return this.sequence;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("sequence")
    public void setSequence (String value) { 
        this.sequence = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("lastUpdate")
    public long getLastUpdate ( ) { 
        return this.lastUpdate;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("lastUpdate")
    public void setLastUpdate (long value) { 
        this.lastUpdate = value;
    }
 
}
