/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class TripTranslate 
        implements java.io.Serializable {
    private static final long serialVersionUID = -4776532866382987920L;
    private String tripPlanId;
    private String language;
    private String name;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("tripPlanId")
    public String getTripPlanId ( ) { 
        return this.tripPlanId;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("tripPlanId")
    public void setTripPlanId (String value) { 
        this.tripPlanId = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("language")
    public String getLanguage ( ) { 
        return this.language;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("language")
    public void setLanguage (String value) { 
        this.language = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("name")
    public String getName ( ) { 
        return this.name;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("name")
    public void setName (String value) { 
        this.name = value;
    }
 
}
